### ISSUE TITLE
Update spacing components in organization lib

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/admin-ui#506]
Experiment:
- [x] Using all using the same color
- [x] Padding and Margins with different colors
- [x] Plugin recommendation

**Comment by eoqmoreno** [comment]
- I separated the margin and padding in two non-semantic colors (pink and purple) and create three props:
1. Type: padding or margin
2. Orientation: vertical or horizontal
3. Token: space-0, space-05, space-1...

- I changed the component name to "spacing" and use the same style as Components Lib

Link to frame: https://www.figma.com/file/dcd9JbVqXdgJ4RlKMWGWt5/Admin-UI-%E2%80%93-File-Organization?node-id=1253%3A27047&t=XFtCcqcxanmQjcHX-1

**Comment by eoqmoreno** [comment]
- Tokens name: maybe we can describe, in component description, that the token value is the number multiplied by 4. What you think?

- I will test the more transparent colors on top of smaller components

- The big problem with the plugin is when you need to remove the instance or select an internal component to work. But this is the common problem in plugins because of layering method. The plugin helps to create automatic measures [like in this form](https://www.figma.com/file/dcd9JbVqXdgJ4RlKMWGWt5/Admin-UI-%E2%80%93-File-Organization?node-id=1267%3A41372&t=f44lFxdpcaLNP4Gd-1)

**Comment by beatrizmilhomem** [comment]
* Tokens name: I think it's less straightforward, but we can launch like this and validate later.

* Transparency: it worked for me!

* Plugin: But are we still proposing that people use it in VTEX? I don't think the layers are a problem, the way you solved it can work really fine for a handoff file.

**Comment by beatrizmilhomem** [comment]
PS: it's the token number multiplied by 16

**Comment by eoqmoreno** [comment]
I did a test using the spacing tokens component here

![Image](https://user-images.githubusercontent.com/26285342/206260724-f6d3e816-6509-400e-8594-f3b9b22bc8f0.png)

**Comment by beatrizmilhomem** [comment]
* Forget about my comment about the multiplication heheh I don't know why I was multiplying the rem value 😬

* The test worked great!

**Comment by eoqmoreno** [comment]
Library published with this description:
> Spacing updates:
> - Updated spacing tokens to follow 4px scaling.
> - Separation of padding and margin by color, as well as vertical and horizontal alignment for ease of use.
> - Updated component name to "spacing"
